### ISSUE TITLE
Allow choosing operations for a watcher

### ISSUE THREAD

**Issue by alcaeus** [manyminds/redkeep#1]
When defining watchers it would be nice if I were able to define which operations a watcher should listen to. Example: I might be able to directly set redundant options when inserting a new object and only need redkeep for updates.

**Comment by sharpner** [comment]
This should be simple. Although that could lead to incosistent data if you define only updates, but don't actually handle the insertion correctly.

But if it's a configurable opt-in feature, I think it's ok to do so.

**Comment by alcaeus** [comment]
> Although that could lead to incosistent data if you define only updates, but don't actually handle the insertion correctly.

You're right, that could be an issue. Another option would be to check if the fields a watcher wants to be set are already set. If they are, great. If not, update them as you always would on insert. That would even remove the need for special configuration.

**Comment by sharpner** [comment]
This would require one additional lookup for each changing dataset :-/ since currently redkeep only rewrites update queries...

**Comment by alcaeus** [comment]
Maybe I'm thinking of it wrong, but the current usecases are:
- Insert: when a document of type a is inserted, check if it includes a reference to an document of type b according to a watcher. If it does, look up the referenced document and redundantly store the indicated properties.
- Update (1): when a document of type a is updated, check if the reference to an document of type b was updated. If it is, look up the referenced document and update the stored properties.
- Update (2): when a document of type b is updated, find all documents of type a that reference the updated document and update the stored properties.

What I'm suggesting affects insert and update (1). Update (2) is not affected.
- For insert, check if the properties to be redundantly stored are already where they belong. If so, don't do anything, assume somebody else (e.g. an ODM or other persistence layer) has taken care of redundantly storing properties. If at least one field is absent, act as if all are missing and update accordingly.
- For update (1), check if the properties to be redundantly stored are being updated along with the reference. If so, don't do anything, assume somebody else has taken care of updating those properties. If at least one field is not being updated, act as if all are missing and update accordingly.

IMO, this would actually reduce the number of lookups to other objects because the library storing the reference probably already has the referenced object in memory and can fill in the required information without doing a database lookup.
